### ISSUE TITLE
로그인 API 응답 에러 (500)

### ISSUE THREAD

**Issue by jungdj** [sparcs-kaist/zabo-server-nodejs#14]
![image](https://user-images.githubusercontent.com/18550028/65492829-9aaa2200-deec-11e9-8631-5b7906fb124f.png)

/api/auth/login 

500 에러 발생

로그가 남지 않음.

**Comment by smartbirdisharvard** [comment]
음... 500 에러가 왜 났는지 전혀 모르겠네요 ㅠㅠ
일단 로그 남도록 코드 수정은 했습니다
